Agora que começa a brincadeira, o primeiro passo é importar o numpy, usando o famoso:

In [1]:
import numpy as np

# CRIANDO ARRAYS

Existem várias formas de criar arrays, pode ser através do método np.array(), usando uma lista ou tupla do python:

In [2]:
arr = np.array([-2, 4.3, 7, 9])

my_tuple = (8, -5, 0, 3.2)
arr2 = np.array(my_tuple)

print('arr = ', arr)
print('arr2 = ', arr2)

arr =  [-2.   4.3  7.   9. ]
arr2 =  [ 8.  -5.   0.   3.2]


Usando o método arange (similar ao range do python)

In [3]:
arr = np.arange(10)
print(arr, '\n')

# Lembrando que arrays podem ter mais de uma dimensão
# cria uma array começando em 2 e até 32 (sem incluí-lo),  pulando cada dois números

arr2 = np.arange(1, 32, 2).reshape(4, 4) # reshape muda o formato da array - nesse caso de (16) para (4x4)
print(arr2)

[0 1 2 3 4 5 6 7 8 9] 

[[ 1  3  5  7]
 [ 9 11 13 15]
 [17 19 21 23]
 [25 27 29 31]]


Usando os métodos 'zeros()' e 'ones()' para criar arrays de 0 e 1, respectivamente:

In [4]:
arr = np.zeros(8) # array contendo 8 'zeros'
print (arr)

arr2 = np.ones((4,3)) # array contendo 12 'uns', no formato 4 x 3
print(arr2)

[ 0.  0.  0.  0.  0.  0.  0.  0.]
[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]


In [5]:
# Método linspace()

arr = np.linspace(1, 100, 10) # de 1 a 100, contendo 10 valores
print(arr, '\n')


# Array vazia com o método empty()

arr2 = np.empty((6,4)) # normalmente a saída é lixo de memória ou zeros
print(arr2, '\n')


# Np.Eye

arr3 = np.eye(4) # eye cria uma array de duas dimensões com 1 na da diagnoal e 0 nos outros elementos
print(arr3)

[   1.   12.   23.   34.   45.   56.   67.   78.   89.  100.] 

[[  6.95324061e-312   6.95304310e-312   6.95305659e-312   9.79597118e-315]
 [  9.79598683e-315   9.79597260e-315   6.95280442e-312   6.95324061e-312]
 [  6.95281148e-312   6.95324131e-312   6.95304310e-312   6.95286325e-312]
 [  9.79597197e-315   9.79597165e-315   6.95280442e-312   6.95324131e-312]
 [  6.95281148e-312   6.95314450e-312   6.95304310e-312   6.95305620e-312]
 [  9.79597165e-315   0.00000000e+000   0.00000000e+000   0.00000000e+000]] 

[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]


## ATRIBUTOS DAS ARRAYS

Existem vários atributos, mas o três principais são .shape , .size e .dtype

In [6]:
arr = np.linspace(.5, 50, 10)

print('.shape: ', arr.shape)    # imprime o formato da array
print('.size: ', arr.size)      # imprime o tamanho da array
print('.dtype: ', arr.dtype)    # imprime o tipo de dado dos elementos

.shape:  (10,)
.size:  10
.dtype:  float64


Outros atributos:

In [7]:
print('.ndim: ', arr.ndim)          # número de dimensões
print('.itemsize: ', arr.size)      # tamanho de cada elemento em bytes

.ndim:  1
.itemsize:  10


## MÉTODOS

Existem inúmeros métodos que nos ajudam a trabalhar com numpy arrays, vou mostrar os mais usados:

In [8]:
arr = np.arange(1,10)
print('array original: ', arr, '\n')

# Como já vimos 'reshape()' muda o formato da array, MAS o número de elementos dos dois formatos tem que coincidir, exemplo:
arr2 = arr.reshape((3,3))
print ('formato 3x3: \n' , arr2, '\n')

array original:  [1 2 3 4 5 6 7 8 9] 

formato 3x3: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 



In [9]:
arr.max() # retorna o valor máximo

9

In [10]:
print(arr.argmax()) # retorna o índice que contém o valor máximo
arr[8] == arr[arr.argmax()]

8


True

In [11]:
arr.min() # retorna o mínimo

1

In [12]:
print(arr.argmin()) # retorna o índice que contém o valor máximo
arr[0] == arr[arr.argmin()]

0


True

In [13]:
arr.mean() # retorna a média

5.0

In [14]:
arr.std() # retorna o desvio padrão

2.5819888974716112

In [15]:
arr.sum() #retorna a soma de todos os elementos da array

45

In [16]:
### FUNÇÕES UNIVERSAIS ###

np.sqrt(arr) # retorna um array com a raiz quadrada de cada elemento

array([ 1.        ,  1.41421356,  1.73205081,  2.        ,  2.23606798,
        2.44948974,  2.64575131,  2.82842712,  3.        ])

In [17]:
np.sin(arr) # retorna um array com o seno de cada elemento

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [18]:
np.cos(arr) # retorna um array com o cosseno de cada elemento

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [19]:
np.exp(arr) # retorna um array com o exponencial cada elemento (e^x)

array([  2.71828183e+00,   7.38905610e+00,   2.00855369e+01,
         5.45981500e+01,   1.48413159e+02,   4.03428793e+02,
         1.09663316e+03,   2.98095799e+03,   8.10308393e+03])

## OPERAÇÕES BÁSICAS

É bem fácil realizar operações matemáticas com arrays 

In [20]:
# vamos criar as arrays A e B para fazer operações com elas

A = np.arange(10)
B = np.arange(10,38,3)

print (' A: ', A, '\n', 'B: ', B)

 A:  [0 1 2 3 4 5 6 7 8 9] 
 B:  [10 13 16 19 22 25 28 31 34 37]


In [21]:
somar = A + B
subtrair = A - B
dividir = A / B
multiplicar = A * B

print('somar: ', somar )
print('subtrair: ', subtrair )
print('dividir: ', dividir )
print('multiplicar: ', multiplicar)

somar:  [10 14 18 22 26 30 34 38 42 46]
subtrair:  [-10 -12 -14 -16 -18 -20 -22 -24 -26 -28]
dividir:  [ 0.          0.07692308  0.125       0.15789474  0.18181818  0.2
  0.21428571  0.22580645  0.23529412  0.24324324]
multiplicar:  [  0  13  32  57  88 125 168 217 272 333]


####  Perceba que se você dividir por zero, numpy não vai dar erro (o código vai rodar), porém vai emitir uma advertência!

In [22]:
B/A     # a array A contém um zero como primeiro elemento

C:\Users\lbour\Anaconda3\envs\k35\lib\site-packages\ipykernel\__main__.py:1: RuntimeWarning: divide by zero encountered in true_divide
  if __name__ == '__main__':


array([         inf,  13.        ,   8.        ,   6.33333333,
         5.5       ,   5.        ,   4.66666667,   4.42857143,
         4.25      ,   4.11111111])

BROADCAST = transmissão

In [23]:
''' Você pode fazer operações envolvendo arrays e um único elemento, dessa forma numpy itera a operação 
do elemento único com todos os componentes da array, exemplo: ''' 

A * 100    # retorna um array com a multiplicação de todos elementos da array por 100

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

## INDEXAÇÃO E FATIAMENTO (SLICING)

O acesso de elementos de uma array, funciona de forma similar ao das listas do Python:

In [24]:
# criar uma array com o quadrado dos números de 1 a 10
arr = np.arange(1, 10) **2
arr

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [25]:
# acessando o primeiro elemento
print('1º elemento: ', arr[0])    # lembrar que índice começa do 0

# acessando o quinto elemento
print ('5º elemento: ', arr[4])   # O quinto elemento é acessado pelo índice 4

1º elemento:  1
5º elemento:  25


In [26]:
# Em um array de duas dimensões (ou mais) existem duas formas de acessar o índice:

arr = arr.reshape((3,3))
print (arr, '\n')

# Usando colchetes duplos [][]
print ('Acessando o elemento 25: ', arr[1][1])

# Ou minha preferência pessoal - separando índices por vírgula
print ('Acessando o elemento 25: ', arr[1,1])

# acessando o último elemento usando o -1
arr[-1, -1] 

[[ 1  4  9]
 [16 25 36]
 [49 64 81]] 

Acessando o elemento 25:  25
Acessando o elemento 25:  25


81

In [27]:
# Para acessar fatias de elementos, usamos o slice [i:i], exemplo

# linha: acessar da linha de índice 0 a linha de índice 2 (excluindo esta) = [0:2]
# coluna: acessar da coluna de índice 0 a coluna de 3 (excluindo esta) = [0:3] - no nosso caso, todas as colunas
print(arr[0:2 , 0:3],'\n')

# outra forma de obter o mesmo resultado é usando [:], que pega todos os elementos
print(arr[0:2 , 0:3])

[[ 1  4  9]
 [16 25 36]] 

[[ 1  4  9]
 [16 25 36]]


In [28]:
# Podemos criar uma nova array com slice de outra

arr2 = arr[ : , 1:3]
arr2

array([[ 4,  9],
       [25, 36],
       [64, 81]])

In [29]:
# Podemor atribuir novos elementos a nossa array, usando slice

arr[1:2, :] = -99
arr

array([[  1,   4,   9],
       [-99, -99, -99],
       [ 49,  64,  81]])

## Uma imagem vale mais que mil palavras:

![Image](http://www.scipy-lectures.org/_images/numpy_indexing.png)

#### SELEÇÃO CONDICIONAL:

Uma forma interessante de selecionar elementos baseado em alguma condição

In [30]:
A = np.arange(10)
print ('A: ', A)

A:  [0 1 2 3 4 5 6 7 8 9]


In [31]:
A > 5 # retorna uma array de variáveis booleanas de acordo com a condição

array([False, False, False, False, False, False,  True,  True,  True,  True], dtype=bool)

In [32]:
# Também odemos criar uma array a partir dessa condição
B = A > 5

In [33]:
# Isso nos dá 2 opções para fazer seleção condicional, passando a condição ou passando o array como índice  

print (A [A > 5])

print (A [B])

# em ambos os casos só retorna os valores que admitem essa condição 

[6 7 8 9]
[6 7 8 9]


## NÚMEROS ALEATÓRIOS:

np.random

In [34]:
# random ou random_sample cria floats aleatórios entre 0 e 1

print (np.random.random(2), '\n')         # passar a quantidade de números desejada
print(np.random.random_sample(4)) 

[ 0.57523608  0.04945749] 

[ 0.63409923  0.46116619  0.07086467  0.27315467]


In [35]:
# randn cria números aleatórios entre -1 e 1 (distribuição normal)

print (np.random.randn(2), '\n')         # passar a quantidade de números desejada
print (np.random.randn(5)) 

[ 0.21341662 -0.04578248] 

[-1.10114593  1.04906643  0.22603859  1.36423983 -1.02432287]


In [36]:
# randint cria números inteiros aleatórios

print (np.random.randint(1,5,4), '\n')   # passar menor valor, maior valor e a quantidade de números desejada
print (np.random.randint(10,20,8)) 

[2 1 1 1] 

[14 13 15 16 17 16 16 15]


Para criar números aleatórios em outro intervalo, basta usar multiplicação e soma para atingir o objetivo

In [37]:
# 10 números aleatórios entre 0 e 5
5 * np.random.random(10)

array([ 0.51082241,  4.31755943,  1.90554176,  2.54231171,  0.65662266,
        3.36074459,  1.52641151,  3.93203519,  3.44842574,  2.43359316])

In [38]:
# 10 números aleatórios entre 5 e 10
5 * np.random.random(10)  + 5

array([ 7.59145368,  9.2303235 ,  8.22579528,  8.15308105,  7.74361074,
        5.66208778,  7.28898889,  9.87313444,  5.27853908,  9.72449187])